version: "3.9"

services:
  consul:
    container_name: "consul"

  rabbitmq:
    container_name: "rabbitmq"

  profit-soft-song-service-backend:
    container_name: "java-backend"

  postgres:
    container_name: "postgres"

  elasticsearch:
    container_name: "elasticsearch"

  profit-soft-song-service-frontend:
    container_name: "js-frontend"